// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Agence.Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Agence.DataAccess.Context
{
    public partial class dbAgenceVersaillesContext : DbContext
    {
        public dbAgenceVersaillesContext()
        {
        }

        public dbAgenceVersaillesContext(DbContextOptions<dbAgenceVersaillesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<VW_tbUsuarios> VW_tbUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<VW_tbUsuarios>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VW_tbUsuarios", "acce");

                entity.Property(e => e.usua_Contrasena).IsRequired();

                entity.Property(e => e.usua_Correo)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.usua_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.usua_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.usua_NombreUsuario)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.usua_NombreUsuarioCreacion)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.usua_NombreUsuarioModificacion).HasMaxLength(100);

                entity.Property(e => e.usua_PersonaNombreCompleto)
                    .IsRequired()
                    .HasMaxLength(301);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}